Itcast.CMS/Itcast.CMS.WebApp/Controllers/AdminNewsListController.cs
using Itcast.CMS.BLL;
using Itcast.CMS.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Itcast.CMS.WebApp.Controllers
{
    public class AdminNewsListController : BaseController//Controller
    {
        NewsInfoService NewsInfoService = new NewsInfoService();

        #region 分页列表
        // GET: AdminNewsList
        public ActionResult Index()
        {
            int pageIndex = Request["pageIndex"] != null ? int.Parse(Request["pageIndex"]) : 1;
            int pageSize = 5;
            int pageCount = NewsInfoService.GetPageCount(pageSize);
            pageIndex = pageIndex < 1 ? 1 : pageIndex;
            pageIndex = pageIndex > pageCount ? pageCount : pageIndex;
            List<NewsInfo> list = NewsInfoService.GetPageList(pageIndex, pageSize);//获取分页的数据
            ViewData["list"] = list;
            ViewData["pageIndex"] = pageIndex;
            ViewData["pageCount"] = pageCount;
            return View();
        }
        #endregion

        #region 获取详细记录
        public ActionResult GetNewsInfoModel()
        {
            int id = int.Parse(Request["id"]);
            NewsInfo newsInfo=NewsInfoService.GetModel(id);
            return Json(newsInfo,JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 删除一条新闻
        public ActionResult DeleteNewsInfo()
        {
            int id = int.Parse(Request["id"]);
            if (NewsInfoService.DeleteInfo(id))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion

        #region 展示添加新闻的表单页面
        public ActionResult ShowAddInfo()
        {
            return View();
        }
        #endregion

        #region 图片文件上传
        public ActionResult FileUpload()
        {
            HttpPostedFileBase postFile = Request.Files["fileUp"];//接受文件数据
            if (postFile == null)
            {
                return Content("no:请选择上传文件");
            }
            else
            {
                string fileName = Path.GetFileName(postFile.FileName);//获取文件名
                string fileExt = Path.GetExtension(fileName);//文件的扩展名称
                if (fileExt == ".jpg")
                {
                    string dir = "/ImagePath/" + DateTime.Now.Year + "/" + DateTime.Now.Month + "/" + DateTime.Now.Day + "/";
                    Directory.CreateDirectory(Path.GetDirectoryName(Request.MapPath(dir)));//创建文件夹
                    string newfileName = Guid.NewGuid().ToString();//新的文件名
                    string fullDir = dir + newfileName + fileExt;//完整的路径
                    postFile.SaveAs(Request.MapPath(fullDir));//保存文件
                    return Content("ok:" + fullDir);
                }
                else
                {
                    return Content("no:文件格式错误！！");
                }
            }
        }
        #endregion

        #region 添加新闻
        [ValidateInput(false)]
        public ActionResult AddNewsInfo(NewsInfo newsInfo)
        {
            newsInfo.SubDateTime = DateTime.Now;
            if (NewsInfoService.AddInfo(newsInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion
    }
}

Itcast.CMS/Itcast.CMS.WebApp/Views/AdminNewsList/Index.cshtml
@{
    Layout = null;
}
@using Itcast.CMS.Model
@using Itcast.CMS.Common

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <link href="~/Content/pageBar.css" rel="stylesheet" />
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#detailDiv").css("display", "none");
            $("#divAdd").css("display", "none");
            $(".detail").click(function () {
                showDetail($(this).attr("ids"));//显示详细信息
            });
            $(".delete").click(function () {
                deleteInfo($(this).attr("ids"),$(this));
            });
            $("#addNews").click(function () {
                addNewsInfo();
            });
        });
        //添加新闻信息
        function addNewsInfo()
        {
            $("#AddFrame").attr("src", "/AdminNewsList/ShowAddInfo");
            $("#divAdd").css("display", "block");
            $('#divAdd').dialog({
                modal: true,
                resizable: true,
                maximizable: true,
                collapsible: true,
                title: "添加新闻",
                width: 700,
                height: 500,
                buttons: [{
                    text: '添加',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //调用子窗体中的方法.
                        var childWindow = $("#AddFrame")[0].contentWindow;//获取子窗体的window对象
                        childWindow.subForm();
                    }
                }, {
                    text: '取消',
                    handler: function () {
                        $('#divAdd').dialog('close');
                    }
                }]
            });
        }

        //添加完成以后调用该方法关闭添加窗口
        function afterAdd() {
            $('#divAdd').dialog('close');
        }

        //删除新闻
        function deleteInfo(id,control) {
            $.messager.confirm("提示", "确定要删除该记录吗?", function (r) {
                if (r) {//该条件成立表示删除该记录
                    //发送异步请求.
                    $.post("/AdminNewsList/DeleteNewsInfo", { "id": id }, function (data) {
                        if (data == "ok")
                        {
                            $(control).parent().parent().remove();
                            $.messager.show({
                                title: '提示',
                                msg: '恭喜删除成功!!',
                                showType: 'show'
                            });
                        }
                        else
                        {
                            $.messager.show({
                                title: '提示',
                                msg: '抱歉，删除失败!!',
                                showType: 'show'
                            });
                        }
                    });

                    

                }
            });
        }
        //显示详细信息
        function showDetail(id) {
            $.post("/AdminNewsList/GetNewsInfoModel", { "id": id }, function (data) {
                $("#title").text(data.Title);
                $("#author").text(data.Author);
                $("#subDateTime").text(ChangeDateFormat(data.SubDateTime));
                $("#msg").html(data.Msg);
            });
            $("#detailDiv").css("display", "block");
            $('#detailDiv').dialog({
                modal: true,
                resizable: true,
                maximizable: true,
                collapsible: true,
                title: "新闻详细",
                width: 400,
                height:300,
                buttons: [{
                    text: '确定',
                    iconCls: 'icon-ok',
                    handler: function () {
                        alert('ok');
                    }
                }, {
                    text: '取消',
                    handler: function () {
                        $('#detailDiv').dialog('close');
                    }
                }]
            });

        }
        //将序列化成json格式后日期(毫秒数)转成日期格式
        function ChangeDateFormat(cellval) {
            var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));
            var month = (date.getMonth() + 1) < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
            var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
            return date.getFullYear() + "-" + month + "-" + currentDate;
        }

    </script>

    <title>Index</title>
</head>
<body>
    <div>
        <a href="javascript:void(0)" id="addNews">添加</a>
        <table width="100%">
            <tr>
                <th>编号</th>
                <th>标题</th>
                <th>作者</th>
                <th>时间</th>
                <th>操作</th>
            </tr>
            @if (ViewData["list"] != null)
            {
                foreach (NewsInfo newsInfo in (List<NewsInfo>)ViewData["list"])
                {
                    <tr>
                        <td>@newsInfo.Id</td>
                        <td>@newsInfo.Title</td>
                        <td>@newsInfo.Author</td>
                        <td>@newsInfo.SubDateTime</td>
                        <td>
                            <a href="javascript:void(0)" class="detail" ids="@newsInfo.Id">详细</a><br>
                            <a href="javascript:void(0)" class="delete" ids="@newsInfo.Id">删除</a>
                        </td>
                    </tr>
                }
                    <tr><td colspan=5 class="page_nav">
                        @Html.Raw(PageBar.GetPageBar((int)ViewData["pageIndex"], (int)ViewData["pageCount"]))
                    </td></tr>
            }else{
            <a>暂无数据</a>
            }
        </table>

    </div>

    <!---------------- 显示详细信息内容 ------------------->
    <div id="detailDiv">
        <table>
            <tr><td>标题</td><td><span id="title"></span></td></tr>
            <tr><td>作者</td><td><span id="author"></span> </td></tr>
            <tr><td>时间</td><td><span id="subDateTime"></span></td></tr>
            <tr><td>内容</td><td><span id="msg"></span></td></tr>
        </table>
    </div>
    <!---------------- 显示详细信息内容结束 ------------------->

    <!---------------- 添加新闻信息页 ------------------->
    <div id="divAdd" style="overflow:hidden">
        <iframe id="AddFrame" frameborder="0" width="100%" height="100%" scrolling="auto"></iframe>
    </div>
    <!---------------- 添加新闻信息页结束 ------------------->
</body>
</html>

Itcast.CMS/Itcast.CMS.WebApp/Views/AdminNewsList/ShowAddInfo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <script src="~/Content/KinderEditor/kindeditor-min.js"></script>
    <link href="~/Content/KinderEditor/themes/default/default.css" rel="stylesheet" />
    <script src="~/Content/KinderEditor/lang/zh_CN.js"></script>
    <script src="~/Content/KinderEditor/plugins/code/prettify.js"></script>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/MyAjaxForm.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function (K) {
            var editor1 = K.create('#MsgContent', {
                cssPath: '/Content/KinderEditor/plugins/code/prettify.css',
                uploadJson: '/Content/KinderEditor/asp.net/upload_json.ashx',
                fileManagerJson: '/Content/KinderEditor/asp.net/file_manager_json.ashx',
                allowFileManager: true,
                afterBlur: function () { this.sync(); },//注意这里（异步提交时需要同步）
                afterCreate: function () {
                    var self = this;
                    self.sync();//把富文本编辑器的内容放到  文本域里面去。

                }
            });
            prettyPrint();//注意要调用该方法.
        });
        $(function () {
            fileUpload();
        });
        function fileUpload() {
            $("#btnFileUp").click(function () {
                if ($("#fileUpImage").val() == "") {
                    $.messager.alert("提示", "请选择上传的图片文件", "info");
                    return;
                }
                $("#form1").ajaxSubmit({
                    type: "post",
                    url: "/AdminNewsList/FileUpload",
                    success: function (data) {
                        var serverData = data.split(':');
                        if (serverData[0] == "ok") {
                            $("#hidImagePath").val(serverData[1]);//将路径赋值给了隐藏域，提交表单时将提交到服务端保存到数据库.
                            $("#showImage").append("<img src='"+serverData[1]+"' width='40px' height='40px'/>");
                        } else {
                            $.messager.alert("提示", serverData[1], "info");
                        }
                    }
                });
            });
        }
        ////提交表单
        function subForm() {
            $("#form1").submit();
        }
        function afterAdd() {
            window.parent.afterAdd();
        }

    </script>
    <title>添加新闻信息</title>
</head>
<body>
    <div> 
        @using (Ajax.BeginForm("AddNewsInfo","AdminNewsList",new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" },new {id="form1"})) {
        <table>
            <tr>
                <td>新闻标题</td>
                <td><input type="text" name="Title"/></td>
            </tr>
            <tr>
                <td>作者</td>
                <td><input type="text" name="Author" /></td>
            </tr>
            <tr>
                <td>上传图片</td>
                <td>
                    <input type="file" name="fileUp" id="fileUpImage"/>
                    <input type="submit" name="上传图片" id="btnFileUp" />
                    <input type="hidden" id="hidImagePath" name="ImagePath" />
                    <div id="showImage"></div>
                </td>
            </tr>
            <tr>
                <td>新闻内容</td>
                <td>
                    <textarea id="MsgContent" cols="100" rows="8" style="width: 500px; height:200px; visibility: hidden;" name="Msg"></textarea>
                </td>
            </tr>
        </table>
        }
    </div>
</body>
</html>